language: python
python:
- "2.7"
addons:
  apt:
    packages:
    - python-numpy
    - libatlas-base-dev
    - gfortran
    - python-scipy
install:
- pip install pillow
script: nosetests
sudo: false
virtualenv:
  system_site_packages: true
