language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - python-numpy
    - libatlas-base-dev
    - gfortran
install:
- pip install pillow
- pip install scipy
script: nosetests
sudo: false
